#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions-rocev2

# NOTE: To launch without the runParallel, do the following:
#
#           mpirun -np $NPROCS simpleFoam -parallel
#
runParallel simpleFoam $1

# ----------------------------------------------------------------- end-of-file
